version: '3.8'

services:
  pact-broker:
    image: pactfoundation/pact-broker
    ports:
      - "9292:9292"
    volumes:
      - ./broker:/var/pact_broker
    environment:
      PACT_BROKER_DATABASE_ADAPTER: sqlite
      PACT_BROKER_DATABASE_NAME: /var/pact_broker/pact_broker.sqlite3
      PACT_BROKER_LOG_LEVEL: DEBUG
